language: java
jdk:
- oraclejdk8
before_install: wget https://download-cf.jetbrains.com/mps/2018.1/MPS-2018.1.zip
before_install: wget https://github.com/diederikd/ProjectBrowserPlugin/releases/tag/2017.3
install: unzip MPS-2018.1.zip
install: unzip ProjectBrowserPlugin.zip
script: ant -Dmps_home=./MPS\ 2018.1 -Durl_home=./ProjectBrowserPlugin clean generate assemble
