language: java
jdk:
- oraclejdk8
before_install:
- wget https://download-cf.jetbrains.com/mps/2018.1/MPS-2018.1.zip
- wget https://guest:@build.mbeddr.com/repository/downloadAll/Mbeddr2_Mbeddr_Gradle_platform/85319:id/artifacts.zip
install: 
- unzip MPS-2018.1.zip
- unzip artifacts.zip
script: ant -Dmps_home=./MPS\ 2018.1 -Dmbeddr_home=./com.mbeddr.platform clean generate assemble
