language: java
jdk:
- oraclejdk8
before_install:
- wget https://download-cf.jetbrains.com/mps/2018.3/MPS-2018.3.zip
- wget https://github.com/mbeddr/mbeddr.core/releases/download/nightly-619/platform-distribution-1.2.21172.355f4af-MPS-2018.3.2.zip
- wget https://github.com/diederikd/ProjectBrowserPlugin/releases/download/20180706165159-c823013/ProjectBrowserPlugin.zip
install: 
- unzip MPS-2018.3.zip
- unzip platform-distribution-1.2.21172.355f4af-MPS-2018.3.2.zip
script: ant -Dmps_home=./MPS\ 2018.3 -Dmbeddr_home=./plugins -Durl_home=. clean generate assemble
