package Facts.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AmountType = 0;
  public static final int Concept = 1;
  public static final int DateTimeType = 2;
  public static final int DateType = 3;
  public static final int DateValue = 4;
  public static final int DatetimeValue = 5;
  public static final int Entity = 6;
  public static final int EntitySelection = 7;
  public static final int EntityTable = 8;
  public static final int EntityType = 9;
  public static final int EntityTypeInRole = 10;
  public static final int EntityTypeReference = 11;
  public static final int EntityValue = 12;
  public static final int Enumeration = 13;
  public static final int EnumerationType = 14;
  public static final int EnumerationValue = 15;
  public static final int EventDateTime = 16;
  public static final int Fact = 17;
  public static final int FactBase = 18;
  public static final int FactModel = 19;
  public static final int FactTable = 20;
  public static final int FactType = 21;
  public static final int FactTypeInRole = 22;
  public static final int FactTypeWord = 23;
  public static final int FactTypeWordRole = 24;
  public static final int FactTypeWordVerb = 25;
  public static final int FactTypeWording = 26;
  public static final int FactValue = 27;
  public static final int FactWord = 28;
  public static final int FactWordRole = 29;
  public static final int FactWordText = 30;
  public static final int FactWordValue = 31;
  public static final int FactWordVerb = 32;
  public static final int FactWording = 33;
  public static final int Identifier = 34;
  public static final int Instance = 35;
  public static final int IntegerType = 36;
  public static final int IntegerValue = 37;
  public static final int KnownAt = 38;
  public static final int RealType = 39;
  public static final int Role = 40;
  public static final int RoleReference = 41;
  public static final int RoleReferenceExpression = 42;
  public static final int RoleReferenceOperation = 43;
  public static final int RoleType = 44;
  public static final int RoleTypeEntityType = 45;
  public static final int RoleTypeValueType = 46;
  public static final int Specializes = 47;
  public static final int StringType = 48;
  public static final int StringValue = 49;
  public static final int TimeType = 50;
  public static final int TimeValue = 51;
  public static final int ValidityFrom = 52;
  public static final int ValidityTo = 53;
  public static final int Value = 54;
  public static final int ValueType = 55;
  public static final int Variable = 56;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x2aacdfbf487f43acL, 0xa43119468403f2c5L);
    builder.put(0x5357f1c89b6339f7L, AmountType);
    builder.put(0xe475eafb2f3f32cL, Concept);
    builder.put(0x432375ab98050cb7L, DateTimeType);
    builder.put(0xe475eafb2f45688L, DateType);
    builder.put(0xe475eafb30e53bcL, DateValue);
    builder.put(0x432375ab9804ef36L, DatetimeValue);
    builder.put(0xab4c0de8e6a127fL, Entity);
    builder.put(0x1dfdebe1e8c418e7L, EntitySelection);
    builder.put(0xab4c0de8e6a1380L, EntityTable);
    builder.put(0x6fc40fa1299d5a0L, EntityType);
    builder.put(0xe475eafb2f3f362L, EntityTypeInRole);
    builder.put(0x1dfdebe1e84f27e5L, EntityTypeReference);
    builder.put(0xab4c0de8e6a1284L, EntityValue);
    builder.put(0x432375ab97df4172L, Enumeration);
    builder.put(0x432375ab97df41d9L, EnumerationType);
    builder.put(0x432375ab97ff120aL, EnumerationValue);
    builder.put(0x337a9c0102b948b5L, EventDateTime);
    builder.put(0xe475eafb2f47ca7L, Fact);
    builder.put(0xe475eafb2f49215L, FactBase);
    builder.put(0xe475eafb2f3fbcaL, FactModel);
    builder.put(0xe475eafb2f67893L, FactTable);
    builder.put(0xe475eafb2f3f32dL, FactType);
    builder.put(0x7131b251f0ec0054L, FactTypeInRole);
    builder.put(0x33810783f7eaea38L, FactTypeWord);
    builder.put(0x33810783f7eaea39L, FactTypeWordRole);
    builder.put(0x33810783f7f6ffb4L, FactTypeWordVerb);
    builder.put(0x33810783f7eaea37L, FactTypeWording);
    builder.put(0x6d9151c34d5925acL, FactValue);
    builder.put(0x3523753238421805L, FactWord);
    builder.put(0x3523753238421802L, FactWordRole);
    builder.put(0x4d7da095199f67e0L, FactWordText);
    builder.put(0x3523753238421803L, FactWordValue);
    builder.put(0x3523753238421804L, FactWordVerb);
    builder.put(0x33810783f82657e7L, FactWording);
    builder.put(0x7131b251f0eafc6bL, Identifier);
    builder.put(0x432375ab97df4163L, Instance);
    builder.put(0xe475eafb2f3f366L, IntegerType);
    builder.put(0xe475eafb30d95eaL, IntegerValue);
    builder.put(0x60a1274b21e189e4L, KnownAt);
    builder.put(0x5357f1c89b4c8c6bL, RealType);
    builder.put(0xe475eafb2f3f32eL, Role);
    builder.put(0x33810783f7e44d86L, RoleReference);
    builder.put(0x3999e68db4f50593L, RoleReferenceExpression);
    builder.put(0x3999e68db532981bL, RoleReferenceOperation);
    builder.put(0x74b74a6520ce61eL, RoleType);
    builder.put(0x3999e68db5296fe4L, RoleTypeEntityType);
    builder.put(0x3999e68db5296fe5L, RoleTypeValueType);
    builder.put(0x60a1274b2203d5eaL, Specializes);
    builder.put(0xe475eafb2f3f365L, StringType);
    builder.put(0xe475eafb30d95f0L, StringValue);
    builder.put(0x432375ab97f1465cL, TimeType);
    builder.put(0x432375ab9804ef1fL, TimeValue);
    builder.put(0x1bdede51790b01a4L, ValidityFrom);
    builder.put(0x1bdede51790b01a8L, ValidityTo);
    builder.put(0xe475eafb30d415aL, Value);
    builder.put(0xe475eafb2f3f32fL, ValueType);
    builder.put(0xe475eafb2f47cacL, Variable);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
