package MenuPlugin.plugin;

/*Generated by MPS */

import jetbrains.mps.workbench.action.BaseAction;
import javax.swing.Icon;
import org.jetbrains.annotations.NotNull;
import com.intellij.openapi.actionSystem.AnActionEvent;
import java.util.Map;
import com.intellij.openapi.actionSystem.ActionManager;
import com.intellij.openapi.actionSystem.DefaultActionGroup;
import com.intellij.openapi.actionSystem.IdeActions;

public class Action_Add_Action extends BaseAction {
  private static final Icon ICON = null;

  public Action_Add_Action() {
    super("Add Menus", "", ICON);
    this.setIsAlwaysVisible(true);
    this.setExecuteOutsideCommand(false);
  }
  @Override
  public boolean isDumbAware() {
    return true;
  }
  @Override
  public void doExecute(@NotNull final AnActionEvent event, final Map<String, Object> _params) {
    ActionManager am = ActionManager.getInstance();
    DefaultActionGroup mainMenu = (DefaultActionGroup) am.getAction(IdeActions.GROUP_MAIN_MENU);
    DefaultActionGroup AnalyzeMenu = (DefaultActionGroup) am.getAction(IdeActions.GROUP_ANALYZE);
    DefaultActionGroup helpMenu = (DefaultActionGroup) am.getAction("HelpMenu");
    mainMenu.add(helpMenu);
    mainMenu.add(AnalyzeMenu);
  }
}
