package SQL.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class CREATEPROCEDURE_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.newLine();
    tgs.append("DELIMITER //");
    tgs.newLine();
    tgs.append("CREATE PROCEDURE ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
    tgs.append(" (");
    for (SNode parameter : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0x8941e8e48f174830L, 0xb99182ab0ce69beeL, 0x1bdede5178c95481L, 0x1bdede5178c9a008L, "parameters")))) {
      tgs.appendNode(parameter);
      if (parameter != ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0x8941e8e48f174830L, 0xb99182ab0ce69beeL, 0x1bdede5178c95481L, 0x1bdede5178c9a008L, "parameters"))).last()) {
        tgs.append(",");
      }
    }
    tgs.append(")");
    tgs.newLine();
    tgs.newLine();
    tgs.append("COMMENT '");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x8941e8e48f174830L, 0xb99182ab0ce69beeL, 0x1bdede5178c95481L, 0x1bdede5178e54244L, "comment")));
    tgs.append("'");
    tgs.newLine();
    tgs.newLine();
    tgs.append("BEGIN");
    tgs.newLine();
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0x8941e8e48f174830L, 0xb99182ab0ce69beeL, 0x1bdede5178c95481L, 0x1bdede5178c95484L, "statements"))) {
      tgs.appendNode(item);
    }
    tgs.append("END //");
    tgs.newLine();
    tgs.append("DELIMITER ;");
    tgs.newLine();
    tgs.newLine();

  }
}
