SET FOREIGN_KEY_CHECKS=0;
USE Test;
DROP TABLE IF EXISTS TestTable;

CREATE TABLE IF NOT EXISTS Test.Persoon
(Id MEDIUMINT NOT NULL AUTO_INCREMENT,
column1 INT,
column2 INT
, PRIMARY KEY (Id));

CREATE TABLE IF NOT EXISTS Test.Auto
(eigenaar MEDIUMINT,
INDEX (eigenaar), 
FOREIGN KEY (eigenaar) REFERENCES ABC(Id),
kleur ENUM('Zwart', 'Rood', 'Wit')
);
CREATE PROCEDURE procedure_abc ( parm1 MEDIUMINT)
BEGIN
CREATE TABLE IF NOT EXISTS test.ABC
(Id MEDIUMINT
);
INSERT INTO ABC () VALUES ()END
