package Simulation.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.cells.EditorCell;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.editor.runtime.cells.AbstractCellAction;
import Simulation.behavior.Testcases__BehaviorDescriptor;

public class ExecuteTests {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.CLICK, new ExecuteTests.ExecuteTests_CLICK(node));
  }
  public static class ExecuteTests_CLICK extends AbstractCellAction {
    /*package*/ SNode myNode;
    public ExecuteTests_CLICK(SNode node) {
      this.myNode = node;
    }
    public String getDescriptionText() {
      return "Execute tests";
    }
    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }
    public void execute_internal(EditorContext editorContext, SNode node) {
      Testcases__BehaviorDescriptor.executeTests_idws$rq35Qdm.invoke(node);
    }
  }
}
