package Facts.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class RoleReferenceExpression_Constraints extends BaseConstraintsDescriptor {
  public RoleReferenceExpression_Constraints() {
    super(MetaAdapterFactory.getConcept(0x2aacdfbf487f43acL, 0xa43119468403f2c5L, 0x3999e68db4f50593L, "Facts.structure.RoleReferenceExpression"));
  }

}
