package DateTime.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.descriptor.AbstractEditorBuilder;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Indent;
import DateTime.behavior.Months__BehaviorDescriptor;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;

/*package*/ class Months_EditorBuilder_a extends AbstractEditorBuilder {
  @NotNull
  private SNode myNode;

  public Months_EditorBuilder_a(@NotNull EditorContext context, @NotNull SNode node) {
    super(context);
    myNode = node;
  }

  @NotNull
  @Override
  public SNode getNode() {
    return myNode;
  }

  /*package*/ EditorCell createCell() {
    return createCollection_qvzmak_a();
  }

  private EditorCell createCollection_qvzmak_a() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Indent());
    editorCell.setCellId("Collection_qvzmak_a");
    editorCell.setBig(true);
    editorCell.setCellContext(getCellFactory().getCellContext());
    editorCell.addEditorCell(createProperty_qvzmak_a0());
    if (nodeCondition_qvzmak_a1a()) {
      editorCell.addEditorCell(createConstant_qvzmak_b0());
    }
    if (nodeCondition_qvzmak_a2a()) {
      editorCell.addEditorCell(createConstant_qvzmak_c0());
    }
    return editorCell;
  }
  private boolean nodeCondition_qvzmak_a1a() {
    return ((double) Months__BehaviorDescriptor.AantalMaanden_idbTj1CmnGi4.invoke(myNode) == 1);
  }
  private boolean nodeCondition_qvzmak_a2a() {
    return ((double) Months__BehaviorDescriptor.AantalMaanden_idbTj1CmnGi4.invoke(myNode) != 1);
  }
  private EditorCell createProperty_qvzmak_a0() {
    CellProviderWithRole provider = new PropertyCellProvider(myNode, getEditorContext());
    provider.setRole("months");
    provider.setNoTargetText("<no months>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(getEditorContext());
    editorCell.setCellId("property_months");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(getEditorContext());
      return manager.createNodeRoleAttributeCell(attributeConcept, provider.getRoleAttributeKind(), editorCell);
    } else
    return editorCell;
  }
  private EditorCell createConstant_qvzmak_b0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "maand");
    editorCell.setCellId("Constant_qvzmak_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_qvzmak_c0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "maanden");
    editorCell.setCellId("Constant_qvzmak_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }
}
